<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UQQQH2B" failures="1" tests="4" name="Test" time="0.173" errors="0" timestamp="2021-09-07T20:01:31 EET">
  <testcase classname="com.Calculator.test.TestCases" name="divTest" time="0.02"/>
  <testcase classname="com.Calculator.test.TestCases" name="multTest" time="0.005">
    <failure type="java.lang.AssertionError" message="error in mult function expected [8] but found [6]">
      <![CDATA[java.lang.AssertionError: error in mult function expected [8] but found [6]
at com.Calculator.test.TestCases.multTest(TestCases.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- multTest -->
  <testcase classname="com.Calculator.test.TestCases" name="subTest" time="0.012"/>
  <testcase classname="com.Calculator.test.TestCases" name="sumTest" time="0.005"/>
</testsuite> <!-- Test -->
